#! /bin/sh
#   __
#  /\ \
#  \ \ \____    ____  _____   __  __  __    ___ ___
#   \ \ '__`\  /',__\/\ '__`\/\ \/\ \/\ \ /' __` __`\
#    \ \ \L\ \/\__, `\ \ \L\ \ \ \_/ \_/ \/\ \/\ \/\ \
#     \ \_,__/\/\____/\ \ ,__/\ \___x___/'\ \_\ \_\ \_\
#      \/___/  \/___/  \ \ \/  \/__//__/   \/_/\/_/\/_/
#                       \ \_\
#                        \/_/

# init
sxhkd &

feh --bg-center ~/.config/wallpaper-debian.png &

polybar wrpd &

xsetroot -cursor_name left_ptr

# monitor config
bspc monitor HDMI-0 -d I II III IV
bspc monitor DP-2 -d V VI VII VIII
bspc monitor DP-5 -d IX X

# style
bspc config border_width         4
bspc config window_gap          12

bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#4c566a"
bspc config focused_border_color  "#bfbcbb"
bspc config presel_feedback_color "#bfbcbb"

# config
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

# rules
bspc rule -a Firefox-esr desktop=^1
bspc rule -a Riot desktop=^2
bspc rule -a discord desktop=^2
bspc rule -a vlc desktop=^9
