#! /bin/sh

#▀█████████▄     ▄████████    ▄███████▄  ▄█     █▄    ▄▄▄▄███▄▄▄▄
#  ███    ███   ███    ███   ███    ███ ███     ███ ▄██▀▀▀███▀▀▀██▄
#  ███    ███   ███    █▀    ███    ███ ███     ███ ███   ███   ███
# ▄███▄▄▄██▀    ███          ███    ███ ███     ███ ███   ███   ███
#▀▀███▀▀▀██▄  ▀███████████ ▀█████████▀  ███     ███ ███   ███   ███
#  ███    ██▄          ███   ███        ███     ███ ███   ███   ███
#  ███    ███    ▄█    ███   ███        ███ ▄█▄ ███ ███   ███   ███
#▄█████████▀   ▄████████▀   ▄████▀       ▀███▀███▀   ▀█   ███   █▀

# init
sxhkd &

feh --bg-center ~/.config/wallpaper-debian.png &

xsetroot -cursor_name left_ptr


# monitor config
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX
bspc monitor DP-5 -d

# style
bspc config border_width         4
bspc config window_gap          12

bspc config focused_border_color  "#b48ead"
bspc config normal_border_color   "#4c566a"
bspc config presel_feedback_color "#b48ead"

# config
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

# rules
bspc rule -a Firefox-esr desktop=^1
bspc rule -a Riot desktop=^2
bspc rule -a discord desktop=^2

